### PR TITLE
[Method] metal && [FIX] update pre-commit-config

### PR DESCRIPTION
**Pull request by charlesfrazier**
- add metal (ICCV 2021) method in meta
- update pre-commit-config:
    - https://github.com/pre-commit/pre-commit-hooks
        v4.0.1 -> v4.6.0
    - https://github.com/psf/black
        21.7b0 -> 24.4.2
    - https://gitlab.com/pycqa/flake8 -> https://github.com/PyCQA/flake8
        3.9.2 -> 7.1.0
- logs:
core/model/backbone/utils/bdc_pool.py:79:5: E741 ambiguous variable name 'I'
core/model/backbone/utils/bdc_pool.py:100:5: E741 ambiguous variable name 'I'
core/model/finetuning/frn_pretrain.py:103:9: F841 local variable 'd' is assigned to but never used
core/model/finetuning/frn_pretrain.py:127:9: F841 local variable 'episode_size' is assigned to but never used
core/model/finetuning/frn_pretrain.py:153:9: F841 local variable 'episode_size' is assigned to but never used
core/model/finetuning/frn_pretrain.py:166:9: F841 local variable 'episode_size' is assigned to but never used
core/model/meta/metal.py:316:13: F841 local variable 'out' is assigned to but never used
core/model/metric/frn.py:82:9: F841 local variable 'd' is assigned to but never used
- future:
update python version from 3.7 to 3.10 or 3.12

### CODE REVIEW

**Comment by VincenDen** [comment]
您好，您需要：
1. 先git clone最新的库，然后修改内容仅包括：您所添加的模型文件、配置文件、其他文件（大部分情况不需要修改），现在您这样File Changes太多，不好检查。
2. 类似项目主页的model_zoo一样提供训练日志，模型文件

**Comment by charlesfrazier** [comment]
@VincenDen 回退到修改pre-commit-config之前的版本了

**Comment by VincenDen** [comment]
可以提供一个训练日志链接吗，包括训练日志、测试日志、训练模型，以验证是否成功实现

**Comment by charlesfrazier** [comment]
https://github.com/RL-VIG/LibFewShot/pull/110/commits/990089f964e3b6d514d3755b3b344ebe605e26ed#diff-a4cd5fd9903a48d80839c1919399a35e8e60f2576de40ee54f68a4ee1f3ea557
reproduce里面应该有相应的内容

**Comment by charlesfrazier** [comment]
https://github.com/charlesfrazier/LibFewShot/blob/add_metal/reproduce/MeTAL/README.md
reproduce里应该有相应的内容

**Comment by charlesfrazier** [comment]
额，我肯能需要更改一下链接，稍等

**Comment by VincenDen** [comment]
如果你是课程同学 可以直接联系助教





------------------ Original ------------------
From: Charles Frazier ***@***.***&gt;
Date: Tue,Jun 25,2024 11:58 AM
To: RL-VIG/LibFewShot ***@***.***&gt;
Cc: Deng Wenxiao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [RL-VIG/LibFewShot] [Method] metal &amp;&amp; [FIX] updatepre-commit-config (PR #110)





 
额，我肯能需要更改一下链接，稍等

**Pull request closed without merging**
